config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home', to: 'site/home#index'
  root to: 'site/home#index'

  devise_for :applicants
  devise_for :recruiters

  namespace :site do
    get 'home/index'
  end

  namespace :applicants_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies do
      resources :candidatures, only: %i[new create]
    end

    resources :candidatures, only: %i[index show]

    resources :proposals, only: %i[index show] do
      put 'accept', on: :member
      put 'decline', on: :member
    end
  end

  namespace :recruiters_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies, only: %i[index show new create edit update]

    resources :candidatures, only: %i[index show] do
      resources :comments, only: %i[new create]

      resources :proposals, only: %i[new create]

      member do
        patch :favorite
        patch :not_favorite
        put :change_application_status
      end
    end

    resources :proposals, only: %i[index show]
  end

  resources :vacancies, only: %i[index show] do
    get 'search', on: :collection
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :recruiter_profile, optional: true
  belongs_to :applicant_profile, optional: true

  validates :postal_code, :street, :number, :complement,
            :neighborhood, :city, :state, presence: true
end

app/models/applicant.rb
# typed: false
# frozen_string_literal: true

class Applicant < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :applicant_profile, dependent: :destroy

  validates :email, uniqueness: true, email: true
  validates :password, length: { minimum: 8 }, if: -> { password.present? }
end

app/models/applicant_profile.rb
class ApplicantProfile < ApplicationRecord
  validates :first_name, :last_name, :birthdate, :rg, :cpf, :gender,
            :civil_status, :professional_goals, presence: true
            
  belongs_to :applicant
  
  has_many :candidatures
  has_many :vacancies, through: :candidatures
  has_many :comments
  has_many :proposals
  has_many :education_levels, inverse_of: :applicant_profile
  
  has_one_attached :avatar
  has_one :address

  accepts_nested_attributes_for :education_levels, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :address
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  validates :reason_application, :status, presence: true
  
  belongs_to :applicant_profile
  belongs_to :vacancy
  has_many :comments
  has_many :proposals
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :applicant_profile
  belongs_to :recruiter_profile
  belongs_to :candidature
end

app/models/education_level.rb
class EducationLevel < ApplicationRecord
  extend Enumerize 
  belongs_to :applicant_profile

  enumerize :course_status, in: { 
    in_progress: 0, 
    completed: 5, 
    suspended: 10 
  }

  enumerize :course_type, in: { 
    undergraduate: 0, 
    postgraduate: 5, 
    high_school: 10,
    elementary_school: 15,
    technical: 20, 
    associate_degree: 25, 
    mba: 30,
    doctorate: 35, 
    specialization: 40 
  }
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  validates :start_date, :salary_offered, :benefits_offered, 
  :job_functions, :company_expectations, :bonus, :additional_information, presence: true
  belongs_to :candidature
end

app/models/recruiter.rb
# typed: false
# frozen_string_literal: true

class Recruiter < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :recruiter_profile, dependent: :destroy

  validates :email, uniqueness: true, email: true
  validates :password, length: { minimum: 8 }, if: -> { password.present? }
end

app/models/recruiter_profile.rb
class RecruiterProfile < ApplicationRecord
  validates :legal_name, :trade_name, :document, :phone, :cell_phone, :sector,
            :number_employee, :about_us, presence: true
            
  belongs_to :recruiter
  has_many :vacancies
  has_many :comments
  has_many :proposals
  has_one_attached :avatar
  has_one :address

  accepts_nested_attributes_for :address
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  before_create :generate_code

  validates :title, :description, :working_model, :salary,
            :location, :vacancy_level_id, :requirements,
            :desired_skill, :contract_type, presence: true

  belongs_to :recruiter_profile
  belongs_to :vacancy_level
  
  has_many :candidatures
  has_many :applicant_profiles, through: :candidatures
  has_many :vacancy_benefits, inverse_of: :vacancy

  accepts_nested_attributes_for :vacancy_benefits, reject_if: :all_blank, allow_destroy: true
  
  # pagination
  paginates_per 5
  
  def self.search(query)
    where("title ILIKE ? OR description ILIKE ? OR code ILIKE ?", 
      "%#{query}%", "%#{query}%", "%#{query}%")
  end

  private
  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end
end

app/models/vacancy_benefit.rb
class VacancyBenefit < ApplicationRecord
  belongs_to :vacancy
end

app/models/vacancy_level.rb
class VacancyLevel < ApplicationRecord
  has_many :vacancies

  def to_s
    level
  end
end

app/controllers/applicants_dashboard_controller.rb
class ApplicantsDashboardController < ApplicationController
  before_action :authenticate_applicant!
  layout 'applicants_dashboard'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    if current_applicant
      current_applicant.applicant_profile.nil? ?
        new_applicants_dashboard_profile_path :
        applicants_dashboard_home_index_path
    elsif current_recruiter
      current_recruiter.recruiter_profile.nil? ?
        new_recruiters_dashboard_profile_path :
        recruiters_dashboard_home_index_path
    end
  end

  private
  def layout_by_resource
    if devise_controller? && resource_name == :recruiter
      "authenticate_recruiter"
    elsif devise_controller? && resource_name == :applicant
      "authenticate_applicant"
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  def index
    @vacancies = Vacancy.includes(:vacancy_level)
      .all
      .order(created_at: :desc)
      .page(params[:page])
  end  
  
  def show
    @vacancy = Vacancy.find(params[:id])
    unless @vacancy.status == 'Ativo'
      redirect_to vacancies_path
    end
    rescue ActiveRecord::RecordNotFound
    redirect_to vacancies_path
  end

  def search
    @query = params[:q]
    @vacancies = Vacancy.search(@query).page(params[:page])
    if @vacancies.empty?
      flash.now[:alert] = "Nenhuma vaga encontrada"
    end
    if @query.blank?
      flash.now[:alert] = "Campo de busca não pode ficar em branco"
    end
    render :index
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
  def applicant_has_profile?
    current_applicant.applicant_profile.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def total_vacancies
    vacancies = Vacancy.all.count
  end

  def flash_class(type)
    case type
    when 'notice'
      'alert-success'
    when 'error'
      'alert-error'
    when 'alert'
      'alert-warning'
    else
      ''
    end
  end

  def badge_class_for_status(status)
    case status
    when "Ativo"
      "success"
    when "Pausada"
      "warning"
    when "Cancelada"
      "danger"
    else
      "secondary"
    end
  end

  def full_name(applicant_profile)
    "#{applicant_profile.first_name} #{applicant_profile.last_name}"
  end
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
  def recruiter_has_profile?
    current_recruiter.recruiter_profile.present?
  end
end

app/views/shared/_alert.html.erb
<div class="alert <%= flash_class(type) %>">
  <%= message %>
  <button type="button" class="close-btn" onclick="this.parentNode.remove()">&times;</button>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__inner">    
    <div class="footer__column">
      <%= image_tag "logo.png", alt: "Logo", width: "70" %>
      <ul class="footer__column--list">
        <li><a href="#">+55 11 992722723</a></li>
        <li><a href="#">dohiring@support.com</a></li>
      </ul>
      <ul class="footer__column--list footer__column--list-inline">
        <li class="list-inline-item">
          <%= link_to "https://www.linkedin.com/in/cleytonrsilva/", target: "_blank" do %>
            <i class='bx bxl-linkedin-square bx-md'></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to "https://github.com/rcleyton/", target: "_blank" do %>
            <i class='bx bxl-github bx-md'></i>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="footer__column">
      <h3 class="footer__column--title">Institucional</h3>
      <ul class="footer__column--list">
        <li><a href="#">Quem somos</a></li>
        <li><a href="#">Fale conosco</a></li>
        <li><a href="#">Termos de uso</a></li>
        <li><a href="#">Política de privacidade</a></li>
      </ul>
    </div>
    <div class="footer__column">
      <h3 class="footer__column--title">Links úteis</h3>
      <ul class="footer__column--list">
        <li><a href="#">Publicar vagas</a></li>
        <li><a href="#">Buscar vagas</a></li>
        <li><a href="#">Blog</a></li>
      </ul>
    </div>
    <div class="footer__column">
      <h3 class="footer__column--title">Newsletter</h3>
      <form action="#" class="footer__column--form">
        <input type="text" placeholder="Digite seu email">
        <button type="submit">Assinar</button>
      </form>
      <p class="newsletter_text">Assine a newsletter para receber atualizações</p>
    </div>
  </div>
  <div class="footer__copy">
    <span>©<%= DateTime.now.year %> doHiring. 
      <a href="https://www.linkedin.com/in/cleytonrsilva/" target="_blank">
        Desenvolvidor por Cleyton R. Silva</span>
      </a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
  <div class="navbar">
    <i class='bx bx-menu'></i>
    <div class="logo">
      <%= link_to "doHiring", root_path %>
    </div>
    <div class="nav-links">
      <div class="sidebar-logo">
        <span class="logo-name">doHiring</span>
        <i class='bx bx-x' ></i>
      </div>
      <ul class="links">
        <li>
          <a href="#">Entrar</a>
          <i class='bx bxs-chevron-down htmlcss-arrow arrow'></i>
          <ul class="htmlCss-sub-menu sub-menu">
            <li><%= link_to 'Sou cadidato', new_applicant_session_path %></li>
            <li><%= link_to 'Sou recrutador', new_recruiter_session_path %></li>
          </ul>
        </li>
        <li>
          <a href="#">Registrar</a>
          <i class='bx bxs-chevron-down js-arrow arrow'></i>
          <ul class="js-sub-menu sub-menu">
            <li><%= link_to 'Como candidato', new_applicant_registration_path %></li>
            <li><%= link_to 'Como empresa', new_recruiter_registration_path %></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="search-box">
      <i class='bx bx-search'></i>
      <div class="input-box">
        <input type="text" placeholder="Buscar..">
      </div>
    </div>
  </div>
</nav>