config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home', to: 'site/home#index'
  root to: 'site/home#index'

  devise_for :applicants
  devise_for :recruiters

  namespace :site do
    get 'home/index'
  end

  namespace :applicants_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies do
      resources :candidatures, only: %i[new create]
    end

    resources :candidatures, only: %i[index show]

    resources :proposals, only: %i[index show] do
      put 'accept', on: :member
      put 'decline', on: :member
    end
  end

  namespace :recruiters_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies, only: %i[index show new create edit update]

    resources :candidatures, only: %i[index show] do
      resources :comments, only: %i[new create]

      resources :proposals, only: %i[new create]

      member do
        patch :favorite
        patch :not_favorite
        put :change_application_status
      end
    end

    resources :proposals, only: %i[index show]
  end

  resources :vacancies, only: %i[index show] do
    get 'search', on: :collection
  end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  validates :start_date, :salary_offered, :benefits_offered, 
  :job_functions, :company_expectations, :bonus, :additional_information, presence: true
  belongs_to :candidature
end

app/controllers/applicants_dashboard/candidatures_controller.rb
class ApplicantsDashboard::CandidaturesController < ApplicantsDashboardController
  def index
    @candidatures = Candidature.where(applicant_profile_id: current_applicant)
  end

  def show
    @candidature = Candidature.find(params[:id])
    @comments = Comment.all
  end

  def new
    @candidature = Candidature.new
  end

  def create
    @candidature = Candidature.new(candidature_params)
    @candidature.status = "Candidatura Enviada"
    if @candidature.save
      redirect_to applicants_dashboard_candidature_path(@candidature)
      flash[:notice] = "Candidatura enviada com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  private
  def candidature_params
    params.require(:candidature).permit(:reason_application, :vacancy_id, 
    :applicant_profile_id, :status)
  end
end

app/controllers/applicants_dashboard/home_controller.rb
class ApplicantsDashboard::HomeController < ApplicantsDashboardController
  def index
    @candidatures = Candidature.where(applicant_profile_id: current_applicant)
  end
end

app/controllers/applicants_dashboard/profile_controller.rb
class ApplicantsDashboard::ProfileController < ApplicantsDashboardController
  before_action :profile_access_management, only: %i[ show edit ]

  def show
  end

  def new
    redirect_to applicants_dashboard_profile_path(current_applicant.applicant_profile) if 
    current_applicant.applicant_profile.present?
    @applicant_profile = ApplicantProfile.new
    @applicant_profile.build_address
  end

  def create
    @applicant_profile = ApplicantProfile.new(applicant_profile_params)
    if @applicant_profile.save
      redirect_to applicants_dashboard_profile_path(@applicant_profile)
      flash[:notice] = "Perfil criado com sucesso."
    else  
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  def edit
  end

  def update
    @applicant_profile = ApplicantProfile.find(params[:id])
    if @applicant_profile.update(applicant_profile_params)
      redirect_to applicants_dashboard_profile_path
      flash[:notice] = "Perfil atualizado com sucesso."
      puts @applicant_profile.errors.full_messages
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def applicant_profile_params
    params.require(:applicant_profile).permit(:applicant_id, :avatar, :first_name,
    :last_name, :birthdate, :rg, :cpf, :gender, :civil_status, :professional_goals, 
    address_attributes: [
      :id, :street, :number, :postal_code, :complement, :neighborhood, :city, :state], 
    education_levels_attributes: [:id, :course_name, :course_type, :institution_name, 
      :course_status, :start_date, :end_date, :expected_end_date, :_destroy])
  end

  def profile_access_management
    @applicant_profile = ApplicantProfile.find(params[:id])
    @education_levels = @applicant_profile.education_levels
    redirect_to applicants_dashboard_home_index_path if @applicant_profile != current_applicant.applicant_profile
    rescue ActiveRecord::RecordNotFound
    redirect_to applicants_dashboard_home_index_path
  end

end

app/controllers/applicants_dashboard/proposals_controller.rb
class ApplicantsDashboard::ProposalsController < ApplicantsDashboardController
  def index
    @applicant = current_applicant
    if @applicant.applicant_profile.present?
      @proposals = @applicant.applicant_profile.proposals
    else
      redirect_to new_applicants_dashboard_profile_path
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def accept
    @proposal = Proposal.find(params[:id])
    @proposal.update(status: 'Aceita')
    redirect_to applicants_dashboard_proposal_path(@proposal)
  end

  def decline
    @proposal = Proposal.find(params[:id])
    @proposal.update(status: 'Recusada')
    redirect_to applicants_dashboard_proposal_path(@proposal)
  end
end

app/controllers/applicants_dashboard_controller.rb
class ApplicantsDashboardController < ApplicationController
  before_action :authenticate_applicant!
  layout 'applicants_dashboard'
end

app/controllers/recruiters_dashboard/proposals_controller.rb
class RecruitersDashboard::ProposalsController < RecruitersDashboardController
  def index
    @recruiter = current_recruiter
    if @recruiter.recruiter_profile.present?
      @proposals = @recruiter.recruiter_profile.proposals
    else
      redirect_to new_recruiters_dashboard_profile_path
      flash[:alert] = "Complete seu perfil antes de enviar propostas."
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
    @candidature = Candidature.find(params[:candidature_id])
    @applicant_profile_id = @candidature.applicant_profile_id
  end

  def create
    puts @candidature = Candidature.find(params[:candidature_id])
    @applicant_profile_id = @candidature.applicant_profile_id
    @proposal = Proposal.new(proposal_params)
    if @proposal.save
      redirect_to recruiters_dashboard_proposal_path(@proposal)
      flash[:notice] = "Proposta enviada com sucesso."
    else  
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  private
  def proposal_params
    params.require(:proposal).permit(:start_date, :salary_offered, :benefits_offered, 
    :job_functions, :company_expectations, :candidature_id, :applicant_profile_id, :recruiter_profile_id,
    :bonus, :additional_information)
  end
end

app/views/applicants_dashboard/proposals/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10 col-12">
      <h3 class="mb-4">Minhas propostas</h3>
      <% if @proposals.empty? %>
        <div class="card text-center mb-5 bg-warning-subtle">
          <div class="card-body">
            <p class="card-text">Você ainda não recebeu nenhuma proposta</p>
          </div>
        </div>
      <% else %>
        <div class="table-responsive mb-5">
          <table class="table table-hover border border-primary-subtle">
            <thead>
            <tr class="table-primary">
              <th scope="col">Cód Vaga</th>
              <th scope="col">Título da Vaga</th>
              <th scope="col">Ver</th>
            </tr>
            </thead>
            <tbody>
            <% @proposals.each do |proposal| %>
              <tr>
                <td><%= proposal.candidature.vacancy.code %></td>
                <td><%= proposal.candidature.vacancy.title %></td>
                <td>
                  <%= link_to applicants_dashboard_proposal_path(proposal) do %>
                    <%= icon('fa-solid', 'eye') %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>



  

app/views/applicants_dashboard/proposals/show.html.erb
<div class="container">
  <div class="row d-flex mb-4 justify-content-between">
    <div class="col">
      <div class="border rounded-4 p-4">
        <h4 class="border-bottom pb-3">
          Proposta para a vaga de <%= @proposal.candidature.vacancy.title %>
        </h4>
        <div class="row">
          <div class="col-md-6 d-flex justify-content-between py-2">
            <div>Código da vaga</div>
            <strong><%= @proposal.candidature.vacancy.code %></strong>
          </div>
          <div class="col-md-6 d-flex justify-content-between py-2">
            <div>Status</div>
            <strong><%= @proposal.status %></strong>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 d-flex justify-content-between py-2">
            <div>Data de início</div>
            <strong><%= l @proposal.start_date, format: :long %></strong>
          </div>
          <div class="col-md-6 d-flex justify-content-between py-2">
            <div>Salário</div>
            <strong><%= number_to_currency @proposal.salary_offered %></strong>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3 mb-4">
    <div class="col">
      <%= link_to 'Aceitar proposta', accept_applicants_dashboard_proposal_path, class: 'btn btn-success', method: :put %>
      <%= link_to 'Recusar proposta', decline_applicants_dashboard_proposal_path, class: 'mx-3', method: :put %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="mb-4">
        <h2 class="mb-3">Atribuições da vaga</h2>
        <p><%= @proposal.job_functions %></p>
      </div>
      <div class="mb-4">
        <h2 class="mb-3">Expectativa de Empresa</h2>
        <p><%= @proposal.company_expectations %></p>
      </div>
      <div class="mb-4">
        <h2 class="mb-3">Bônus</h2>
        <p><%= @proposal.bonus %></p>
      </div>
      <div class="mb-4">
        <h2 class="mb-3">Benefícios</h2>
        <p><%= @proposal.benefits_offered %></p>
      </div>
      <div class="mb-4">
        <h2 class="mb-3">Informações adicionais</h2>
        <p><%= @proposal.additional_information %></p>
      </div>
    </div>
  </div>
</div>