config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home', to: 'site/home#index'
  root to: 'site/home#index'

  devise_for :applicants
  devise_for :recruiters

  namespace :site do
    get 'home/index'
  end

  namespace :applicants_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies do
      resources :candidatures, only: %i[new create]
    end

    resources :candidatures, only: %i[index show]

    resources :proposals, only: %i[index show] do
      put 'accept', on: :member
      put 'decline', on: :member
    end
  end

  namespace :recruiters_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies, only: %i[index show new create edit update]

    resources :candidatures, only: %i[index show] do
      resources :comments, only: %i[new create]

      resources :proposals, only: %i[new create]

      member do
        patch :favorite
        patch :not_favorite
        put :change_application_status
      end
    end

    resources :proposals, only: %i[index show]
  end

  resources :vacancies, only: %i[index show] do
    get 'search', on: :collection
  end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  before_create :generate_code

  validates :title, :description, :working_model, :salary,
            :location, :vacancy_level_id, :requirements,
            :desired_skill, :contract_type, presence: true

  belongs_to :recruiter_profile
  belongs_to :vacancy_level
  
  has_many :candidatures
  has_many :applicant_profiles, through: :candidatures
  has_many :vacancy_benefits, inverse_of: :vacancy

  accepts_nested_attributes_for :vacancy_benefits, reject_if: :all_blank, allow_destroy: true
  
  # pagination
  paginates_per 5
  
  def self.search(query)
    where("title ILIKE ? OR description ILIKE ? OR code ILIKE ?", 
      "%#{query}%", "%#{query}%", "%#{query}%")
  end

  private
  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end
end

app/controllers/recruiters_dashboard/candidatures_controller.rb
class RecruitersDashboard::CandidaturesController < RecruitersDashboardController
  before_action :find_candidature, only: [:favorite, :not_favorite, :change_application_status]
  
  def index 
    @candidatures = Candidature.where(vacancy: current_recruiter)
  end
  
  def show
    @candidature = Candidature.find(params[:id])
  end

  def favorite
    if @candidature.update(favorite: true)
      redirect_to recruiters_dashboard_candidature_path(@candidature)
    end
  end

  def not_favorite
    if @candidature.update(favorite: false)
      redirect_to recruiters_dashboard_candidature_path(@candidature)
    end
  end

  def change_application_status
    new_status = params[:candidature][:status]
    @candidature.update(status: new_status)
  end
end

private

def find_candidature
  @candidature = Candidature.find(params[:id])
end

app/controllers/recruiters_dashboard/comments_controller.rb
class RecruitersDashboard::CommentsController < RecruitersDashboardController
  def create
    @candidature = Candidature.find(params[:candidature_id])
    @comment = @candidature.comments.create(comment_params)
    if @comment.save
      redirect_to recruiters_dashboard_candidature_path(@candidature)
    else 
      puts @comment.errors.full_messages
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :recruiter_profile_id, :applicant_profile_id)
  end
end

app/controllers/recruiters_dashboard/home_controller.rb
class RecruitersDashboard::HomeController < RecruitersDashboardController
  def index
  end
end

app/controllers/recruiters_dashboard/profile_controller.rb
class RecruitersDashboard::ProfileController < RecruitersDashboardController
  before_action :set_profile, only: %i[ update]
  before_action :profile_access_management, only: %i[ show edit ]

  def show
  end

  def new
    redirect_to  recruiters_dashboard_profile_path(current_recruiter.recruiter_profile) if 
    current_recruiter.recruiter_profile.present?
    @recruiter_profile = RecruiterProfile.new
    @recruiter_profile.build_address
  end

  def create
    @recruiter_profile = RecruiterProfile.new(recruiter_profile_params)
    if @recruiter_profile.save
      redirect_to  recruiters_dashboard_profile_path(@recruiter_profile)
      flash[:notice] = "Perfil criado com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @recruiter_profile.update(recruiter_profile_params)
      redirect_to recruiters_dashboard_profile_path
      flash[:notice] = "Perfil atualizado com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :edit
    end
  end

  private
  def recruiter_profile_params
    params.require(:recruiter_profile).permit(:recruiter_id, :legal_name, :trade_name, :avatar, :about_us,
    :document, :phone, :cell_phone, :sector, :number_employee, address_attributes: [:id, :street, :number, :postal_code,
                                                                                    :complement, :neighborhood,
                                                                                    :city, :state])
  end

  def set_profile
    @recruiter_profile = RecruiterProfile.find(params[:id])
  end

  def profile_access_management
    @recruiter_profile = RecruiterProfile.find(params[:id])    
    redirect_to recruiters_dashboard_home_index_path if @recruiter_profile != current_recruiter.recruiter_profile
    rescue ActiveRecord::RecordNotFound
    redirect_to recruiters_dashboard_home_index_path
  end
  
end

app/controllers/recruiters_dashboard/proposals_controller.rb
class RecruitersDashboard::ProposalsController < RecruitersDashboardController
  def index
    @recruiter = current_recruiter
    if @recruiter.recruiter_profile.present?
      @proposals = @recruiter.recruiter_profile.proposals
    else
      redirect_to new_recruiters_dashboard_profile_path
      flash[:alert] = "Complete seu perfil antes de enviar propostas."
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
    @candidature = Candidature.find(params[:candidature_id])
    @applicant_profile_id = @candidature.applicant_profile_id
  end

  def create
    puts @candidature = Candidature.find(params[:candidature_id])
    @applicant_profile_id = @candidature.applicant_profile_id
    @proposal = Proposal.new(proposal_params)
    if @proposal.save
      redirect_to recruiters_dashboard_proposal_path(@proposal)
      flash[:notice] = "Proposta enviada com sucesso."
    else  
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  private
  def proposal_params
    params.require(:proposal).permit(:start_date, :salary_offered, :benefits_offered, 
    :job_functions, :company_expectations, :candidature_id, :applicant_profile_id, :recruiter_profile_id,
    :bonus, :additional_information)
  end
end

app/controllers/recruiters_dashboard/vacancies_controller.rb
class RecruitersDashboard::VacanciesController < RecruitersDashboardController
  def index 
    @vacancies = Vacancy.where(recruiter_profile_id: current_recruiter)
  end

  def show
    @vacancy = Vacancy.find(params[:id])
    @vacancy_benefits = @vacancy.vacancy_benefits
    rescue ActiveRecord::RecordNotFound
    redirect_to recruiters_dashboard_home_index_path
  end

  def new
    if current_recruiter.recruiter_profile.present?
      @vacancy = Vacancy.new
      @vacancy.build_vacancy_level
    else 
      redirect_to new_recruiters_dashboard_profile_path
      flash[:alert] = "Complete seu perfil antes de publicar uma vaga."
    end
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    if @vacancy.save
      redirect_to recruiters_dashboard_vacancy_path(@vacancy)
      flash[:notice] = "Vaga criada com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  def update
    @vacancy = Vacancy.find(params[:id])

    if @vacancy.update(vacancy_params)
      redirect_to recruiters_dashboard_vacancy_path(@vacancy)
      flash[:notice] = "Vaga atualizada com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :edit
    end
  end

  private
  def vacancy_params
    params.require(:vacancy).permit(:code, :title, :description,
    :working_model, :salary, :location, :recruiter_profile_id, :vacancy_level_id,
    :status, :requirements, :desired_skill, :contract_type, vacancy_benefits_attributes: [:id, :benefit_name, :_destroy])
  end  
end

app/controllers/recruiters_dashboard_controller.rb
class RecruitersDashboardController < ApplicationController
  before_action :authenticate_recruiter!
  layout 'recruiters_dashboard'
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  def index
    @vacancies = Vacancy.includes(:vacancy_level)
      .all
      .order(created_at: :desc)
      .page(params[:page])
  end  
  
  def show
    @vacancy = Vacancy.find(params[:id])
    unless @vacancy.status == 'Ativo'
      redirect_to vacancies_path
    end
    rescue ActiveRecord::RecordNotFound
    redirect_to vacancies_path
  end

  def search
    @query = params[:q]
    @vacancies = Vacancy.search(@query).page(params[:page])
    if @vacancies.empty?
      flash.now[:alert] = "Nenhuma vaga encontrada"
    end
    if @query.blank?
      flash.now[:alert] = "Campo de busca não pode ficar em branco"
    end
    render :index
  end
end

app/views/recruiters_dashboard/vacancies/_form.html.erb
<div class="dashboard__head">
  <div class="dashboard__head--header">
    <div class="dashboard__head--back-btn">
      <%= link_to recruiters_dashboard_home_index_path do %>
        <%= image_tag "angle-left.svg" %>
      <% end %>
    </div>
    <h1 class="dashboard__head--title-page"><%= action_message.capitalize %> vaga</h1>
  </div>
</div>

<div class="profile__body">
  <div class="profile__body--form">
    <%= simple_form_for @vacancy, url: (@vacancy.new_record? ?
                                          recruiters_dashboard_vacancies_path :
                                          recruiters_dashboard_vacancy_path),
                                          data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |form| %>

    <%= form.input :recruiter_profile_id, as: :hidden, input_html: { value: current_recruiter.id} %>
      
    <% if action_name == 'edit' %>
    <div class="form-field">
      <%= form.input :status, collection: ["Ativo", "Pausada", "Expirada", "Cancelada", "Fechada"], include_blank: "Selecione um status",
                    label_html: { class: 'form-label' },
                    input_html: { class: 'form-select'}  %>
      </div>
    <% end %>
    <div class="form-field">
      <%= form.input :title, label_html: { class: 'form-label' } %>
    </div>
    <div class="form-field">
      <%= form.input :description, as: :text, label_html: { class: 'form-label' },
                                  input_html: { rows: 5, cols: 10, class: 'form-control' } %>
    </div>
    <div class="form-field">
      <%= form.input :requirements, label_html: { class: 'form-label' },
                      input_html: { class: 'form-control'} %>
    </div>
    <div class="form-field">        
      <%= form.input :desired_skill, label_html: { class: 'form-label' },
                      input_html: { class: 'form-control' } %>
    </div>
    <div class="form-field">        
      <%= form.input :vacancy_level_id, as: :select, collection: VacancyLevel.all, include_blank: "Selecione o nível da vaga",
                        label_html: { class: 'form-label' },
                        input_html: { class: 'form-select'} %>
    </div>
    <div class="form-field">        
      <%= form.input :working_model, label_html: { class: 'form-label' },
                                  input_html: { class: 'form-control' } %>
    </div>
    <div class="form-field">        
      <%= form.input :salary, label_html: { class: 'form-label' },
                                  input_html: { class: 'form-control' } %>
    </div>
    <div class="form-field">
      <%= form.input :contract_type, label_html: { class: 'form-label' },
                        input_html: { class: 'form-control'} %>
    </div>
    <div class="form-field">    
      <%= form.input :location, label_html: { class: 'form-label' }, input_html: { class: 'form-control'} %>
    </div>
    <h3 class="form-title">Benefícios</h3>
    <template data-nested-form-target="template">
      <%= form.simple_fields_for :vacancy_benefits, VacancyBenefit.new, child_index: 'NEW_RECORD' do |benefits| %>
        <%= render "vacancy_benefit_fields", f: benefits %>
      <% end %>
    </template>

    <%= form.simple_fields_for :vacancy_benefits do |benefits| %>
      <%= render "vacancy_benefit_fields", f: benefits %>
    <% end %>

    <div data-nested-form-target="target"></div>

    <div class="add-benefits">
      <button type="button" data-action="nested-form#add">
        <%= image_tag "plus-circle.svg", width: "24" %>Adicionar benefício
      </button>
    </div>
    <%= form.button :submit, class: 'btn-update' %>

    <% end %>
  </div>
</div>

app/views/recruiters_dashboard/vacancies/_vacancy_benefit_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="form-benefits">
    <%= f.text_field :benefit_name %>
    <button type="button" data-action="nested-form#remove" class="remove-benefit">
      <%= image_tag "trash.svg", width: "24", class: "remove-benetit-icon" %>
    </button>
  </div>
  <%= f.hidden_field :_destroy %>
</div>

app/views/recruiters_dashboard/vacancies/edit.html.erb
<%= render partial: 'form', vacancy: @vacancy, locals: { action_message: "Editar" } %>

app/views/recruiters_dashboard/vacancies/index.html.erb
<div class="dashboard__head">
  <div class="dashboard__head--header">
    <div class="dashboard__head--back-btn">
      <%= link_to recruiters_dashboard_home_index_path do %>
        <%= image_tag "angle-left.svg" %>
      <% end %>
    </div>
    <%= link_to new_recruiters_dashboard_vacancy_path do %>
      <h1 class="dashboard__head--title-page">Publicar vaga &rarr;</h1>
    <% end %>
  </div>
</div>
<div class="dashboard__body">
  <div class="dashboard__content">
    <div class="dashboard__content--card">
      <div class="dashboard__content--card-header">
        <h3>Vagas publicadas</h3>
      </div>
      <div class="dashboard__content--card-body">
        <% if @vacancies.empty? %>
          <p>Nenhuma vaga publicada ainda!</p>
        <% else %>
          <% @vacancies.each do |vacancy| %>
          <div class="content-body">
              <div class="content-body-left">
                <%= image_tag "briefcase-view-outline.svg"%>
                <span><%= vacancy.title %></span>
              </div>
              <%= link_to recruiters_dashboard_vacancy_path(vacancy) do %>
                <%= image_tag "arrow-right.svg" %>
              <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recruiters_dashboard/vacancies/new.html.erb
<%= render partial: 'form', vacancy: @vacancy, locals: { action_message: "Nova" } %>

app/views/recruiters_dashboard/vacancies/show.html.erb
<div class="dashboard__head">
  <div class="dashboard__head--header">
    <div class="dashboard__head--back-btn">
      <%= link_to recruiters_dashboard_home_index_path do %>
        <%= image_tag "angle-left.svg" %>
      <% end %>
    </div>
    <h1 class="dashboard__head--title-page"><%= @vacancy.title %></h1>
  </div>
</div>
<div class="dashboard__body">
  <div class="dashboard__content">
    <div class="dashboard__content--card">
      <div class="dashboard__content--card-header">
        <%= image_tag "info.svg", width: "24" %>
        <h3>Detalhes</h3>
      </div>
      <ul>
        <li>Vaga <%= @vacancy.status.downcase %></li>
        <% if @vacancy.candidatures.empty? %>
          <li>Nenhuma candidatura para essa vaga ainda</li>
        <% else %>
          <li>
            <%= @vacancy.candidatures.count %> candidaturas para esta vaga
          </li>
        <% end %>
        <li>Nível <%= @vacancy.vacancy_level %></li>
        <li>Modelo de trabalho <%= @vacancy.working_model.downcase %></li>
        <li><%= number_to_currency @vacancy.salary %></li>
        <li>Contrato do tipo <%= @vacancy.contract_type %></li>
        <li><%= @vacancy.location %></li>
      </ul>
    </div>
    <div class="dashboard__content--card">
      <div class="dashboard__content--card-header">
        <%= image_tag "description.svg", width: "24" %>
        <h3>Descrição</h3>
      </div>
      <p>
        <%= @vacancy.description %>
      </p>
    </div>
    <div class="dashboard__content--card">
      <div class="dashboard__content--card-header">
        <%= image_tag "requirement.svg", width: "24" %>
        <h3>Requisitos</h3>
      </div>
      <p>
        <%= @vacancy.requirements %>
      </p>
    </div>
    <div class="dashboard__content--card">
      <div class="dashboard__content--card-header">
        <%= image_tag "ability.svg", width: "24" %>
        <h3>Habilidade desejável</h3>
      </div>
      <p>
        <%= @vacancy.desired_skill %>
      </p>
    </div>
    <div class="dashboard__content--card">
      <div class="dashboard__content--card-header">
        <%= image_tag "benefit.svg", width: "24" %>
        <h3>Benefícios</h3>
      </div>
      <ul>
        <% @vacancy_benefits.each do |benefit| %>
          <li><%= benefit.benefit_name %></li>
        <% end %>
      </ul>
    </div>
    <%= button_to 'Editar', edit_recruiters_dashboard_vacancy_path(@vacancy),
                    method: :get, class: 'btn-edit' %>
  </div>
</div>