config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home', to: 'site/home#index'
  root to: 'site/home#index'

  devise_for :applicants
  devise_for :recruiters

  namespace :site do
    get 'home/index'
  end

  namespace :applicants_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies do
      resources :candidatures, only: %i[new create]
    end

    resources :candidatures, only: %i[index show]

    resources :proposals, only: %i[index show] do
      put 'accept', on: :member
      put 'decline', on: :member
    end
  end

  namespace :recruiters_dashboard do
    get 'home/index'

    resources :profile, only: %i[show new create edit update]

    resources :vacancies, only: %i[index show new create edit update]

    resources :candidatures, only: %i[index show] do
      resources :comments, only: %i[new create]

      resources :proposals, only: %i[new create]

      member do
        patch :favorite
        patch :not_favorite
        put :change_application_status
      end
    end

    resources :proposals, only: %i[index show]
  end

  resources :vacancies, only: %i[index show] do
    get 'search', on: :collection
  end
end

app/controllers/applicants_dashboard/home_controller.rb
class ApplicantsDashboard::HomeController < ApplicantsDashboardController
  def index
    @candidatures = Candidature.where(applicant_profile_id: current_applicant)
  end
end

app/controllers/recruiters_dashboard/candidatures_controller.rb
class RecruitersDashboard::CandidaturesController < RecruitersDashboardController
  before_action :find_candidature, only: [:favorite, :not_favorite, :change_application_status]
  
  def index 
    @candidatures = Candidature.where(vacancy: current_recruiter)
  end
  
  def show
    @candidature = Candidature.find(params[:id])
  end

  def favorite
    if @candidature.update(favorite: true)
      redirect_to recruiters_dashboard_candidature_path(@candidature)
    end
  end

  def not_favorite
    if @candidature.update(favorite: false)
      redirect_to recruiters_dashboard_candidature_path(@candidature)
    end
  end

  def change_application_status
    new_status = params[:candidature][:status]
    @candidature.update(status: new_status)
  end
end

private

def find_candidature
  @candidature = Candidature.find(params[:id])
end

app/controllers/recruiters_dashboard/comments_controller.rb
class RecruitersDashboard::CommentsController < RecruitersDashboardController
  def create
    @candidature = Candidature.find(params[:candidature_id])
    @comment = @candidature.comments.create(comment_params)
    if @comment.save
      redirect_to recruiters_dashboard_candidature_path(@candidature)
    else 
      puts @comment.errors.full_messages
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :recruiter_profile_id, :applicant_profile_id)
  end
end

app/controllers/recruiters_dashboard/home_controller.rb
class RecruitersDashboard::HomeController < RecruitersDashboardController
  def index
  end
end

app/controllers/recruiters_dashboard/profile_controller.rb
class RecruitersDashboard::ProfileController < RecruitersDashboardController
  before_action :set_profile, only: %i[ update]
  before_action :profile_access_management, only: %i[ show edit ]

  def show
  end

  def new
    redirect_to  recruiters_dashboard_profile_path(current_recruiter.recruiter_profile) if 
    current_recruiter.recruiter_profile.present?
    @recruiter_profile = RecruiterProfile.new
    @recruiter_profile.build_address
  end

  def create
    @recruiter_profile = RecruiterProfile.new(recruiter_profile_params)
    if @recruiter_profile.save
      redirect_to  recruiters_dashboard_profile_path(@recruiter_profile)
      flash[:notice] = "Perfil criado com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @recruiter_profile.update(recruiter_profile_params)
      redirect_to recruiters_dashboard_profile_path
      flash[:notice] = "Perfil atualizado com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :edit
    end
  end

  private
  def recruiter_profile_params
    params.require(:recruiter_profile).permit(:recruiter_id, :legal_name, :trade_name, :avatar, :about_us,
    :document, :phone, :cell_phone, :sector, :number_employee, address_attributes: [:id, :street, :number, :postal_code,
                                                                                    :complement, :neighborhood,
                                                                                    :city, :state])
  end

  def set_profile
    @recruiter_profile = RecruiterProfile.find(params[:id])
  end

  def profile_access_management
    @recruiter_profile = RecruiterProfile.find(params[:id])    
    redirect_to recruiters_dashboard_home_index_path if @recruiter_profile != current_recruiter.recruiter_profile
    rescue ActiveRecord::RecordNotFound
    redirect_to recruiters_dashboard_home_index_path
  end
  
end

app/controllers/recruiters_dashboard/proposals_controller.rb
class RecruitersDashboard::ProposalsController < RecruitersDashboardController
  def index
    @recruiter = current_recruiter
    if @recruiter.recruiter_profile.present?
      @proposals = @recruiter.recruiter_profile.proposals
    else
      redirect_to new_recruiters_dashboard_profile_path
      flash[:alert] = "Complete seu perfil antes de enviar propostas."
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
    @candidature = Candidature.find(params[:candidature_id])
    @applicant_profile_id = @candidature.applicant_profile_id
  end

  def create
    puts @candidature = Candidature.find(params[:candidature_id])
    @applicant_profile_id = @candidature.applicant_profile_id
    @proposal = Proposal.new(proposal_params)
    if @proposal.save
      redirect_to recruiters_dashboard_proposal_path(@proposal)
      flash[:notice] = "Proposta enviada com sucesso."
    else  
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  private
  def proposal_params
    params.require(:proposal).permit(:start_date, :salary_offered, :benefits_offered, 
    :job_functions, :company_expectations, :candidature_id, :applicant_profile_id, :recruiter_profile_id,
    :bonus, :additional_information)
  end
end

app/controllers/recruiters_dashboard/vacancies_controller.rb
class RecruitersDashboard::VacanciesController < RecruitersDashboardController
  def index 
    @vacancies = Vacancy.where(recruiter_profile_id: current_recruiter)
  end

  def show
    @vacancy = Vacancy.find(params[:id])
    @vacancy_benefits = @vacancy.vacancy_benefits
    rescue ActiveRecord::RecordNotFound
    redirect_to recruiters_dashboard_home_index_path
  end

  def new
    if current_recruiter.recruiter_profile.present?
      @vacancy = Vacancy.new
      @vacancy.build_vacancy_level
    else 
      redirect_to new_recruiters_dashboard_profile_path
      flash[:alert] = "Complete seu perfil antes de publicar uma vaga."
    end
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    if @vacancy.save
      redirect_to recruiters_dashboard_vacancy_path(@vacancy)
      flash[:notice] = "Vaga criada com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :new
    end
  end

  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  def update
    @vacancy = Vacancy.find(params[:id])

    if @vacancy.update(vacancy_params)
      redirect_to recruiters_dashboard_vacancy_path(@vacancy)
      flash[:notice] = "Vaga atualizada com sucesso."
    else
      flash.now[:error] = "Verifique o(s) campo(os) em vermelho."
      render :edit
    end
  end

  private
  def vacancy_params
    params.require(:vacancy).permit(:code, :title, :description,
    :working_model, :salary, :location, :recruiter_profile_id, :vacancy_level_id,
    :status, :requirements, :desired_skill, :contract_type, vacancy_benefits_attributes: [:id, :benefit_name, :_destroy])
  end  
end

app/controllers/recruiters_dashboard_controller.rb
class RecruitersDashboardController < ApplicationController
  before_action :authenticate_recruiter!
  layout 'recruiters_dashboard'
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    flash.now[:success] = "Bem-vindo ao doHiring"
    respond_to do |format|
      format.html 
      format.turbo_stream 
    end
  end
end

app/views/recruiters_dashboard/home/index.html.erb
<div class="dashboard__body">
  <div class="primary__card">
    <% profile_path = recruiter_has_profile? ? 
      edit_recruiters_dashboard_profile_path(current_recruiter.recruiter_profile) : 
      new_recruiters_dashboard_profile_path %>
    <%= link_to profile_path do %>
      <div class="primary__card--box primary__card--edit">
        <%= image_tag "pencil.svg", width: "24" %>
          <span>Editar perfil</span>
      </div>
    <% end %>
    <%= link_to new_recruiters_dashboard_profile_path do %>
      <div class="primary__card--box primary__card--view">
          <%= image_tag "eye.svg", width: "24" %>
          <span>Ver perfil</span> 
      </div>
    <% end %>
    <div class="primary__card--box primary__card--welcome">
      <span>Seja bem-vindo</span>
      <% if recruiter_has_profile? %>
        <h1><%= current_recruiter.recruiter_profile.trade_name %></h1> 
      <% else %>
        <h1>Olá usuário</h1>
      <% end %>   
      <div class="card__btn--signout">
        <%= link_to destroy_recruiter_session_path, data: { turbo_method: :delete}, 
                                                    class: "dropdown-item", 
                                                    method: :delete do %>
          <%= image_tag "exit.svg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="dashboard__body">
  <div class="account__card">
    <h1 class="account__card--title">Conta</h1>
    <div class="account__card--options">
      <div class="option">
        <%= image_tag "envelope.svg"%>
        <span>Mudar email</span>
      </div>
      <%= image_tag "arrow-right.svg" %>
    </div>
    <div class="account__card--options">
      <div class="option">
        <%= image_tag "lock.svg"%>
        <span>Mudar senha</span>
      </div>
      <%= image_tag "arrow-right.svg" %>
    </div>
    <div class="account__card--options">
      <div class="option">
        <%= link_to profile_path do %>
          <%= image_tag "arrow-loop.svg"%>
        <% end %>
        <span>Atualizar perfil</span>
      </div>
      <%= link_to profile_path do %>
        <%= image_tag "arrow-right.svg" %>
      <% end %>
    </div>
  </div>
</div>
<div class="dashboard__body">
  <div class="vacancies__card">
    <h1 class="vacancies__card--title">Vagas</h1>
    <div class="vacancies__card--options">
      <div class="option">
        <%= link_to new_recruiters_dashboard_vacancy_path do %>
          <%= image_tag "suitcase-line.svg" %>
        <% end %>
        <span>Publicar vaga</span>
      </div>
      <%= link_to new_recruiters_dashboard_vacancy_path do %>
        <%= image_tag "arrow-right.svg" %>
      <% end %>
    </div>
    <div class="vacancies__card--options">
      <div class="option">
        <%= link_to recruiters_dashboard_vacancies_path do %>
          <%= image_tag "briefcase-view-outline.svg" %>
        <% end %>
        <span>Ver vagas publicadas</span>
      </div>
      <%= link_to recruiters_dashboard_vacancies_path do %>
        <%= image_tag "arrow-right.svg" %>
      <% end %>
    </div>
  </div>
</div>
<div class="dashboard__body">
  <div class="candidatures__card">
    <h1 class="candidatures__card--title">Candidaturas</h1>
    <div class="candidatures__card--options">
      <div class="option">
        <%= link_to recruiters_dashboard_candidatures_path do %>
          <%= image_tag "account-view-outline.svg" %>
        <% end %>
        <span>Ver candidaturas</span>
      </div>
      <%= link_to recruiters_dashboard_candidatures_path do %>
        <%= image_tag "arrow-right.svg" %>
      <% end %>
    </div>
  </div>
</div>
<div class="dashboard__body">
  <div class="proposals__card">
    <h1 class="proposals__card--title">Propostas</h1>
    <div class="proposals__card--options">
      <div class="option">
        <%= link_to recruiters_dashboard_proposals_path do %>
          <%= image_tag "business-outline.svg" %>
        <% end %>
        <span>Ver propostas enviadas</span>
      </div>
        <%= link_to recruiters_dashboard_proposals_path do %>
          <%= image_tag "arrow-right.svg" %>
        <% end %>
    </div>
  </div>
</div>